### PR TITLE
Refactored image url search, fixed url for link attachments

### LINKED ISSUE #11: Messages with links bridged as "Link was sent: undefined"
Example of message:
```
Feb-17 07:56:55.159 [VKPuppet:vk] debug: Received new message! MessageContext {
  id: 98758,
  conversationMessageId: 26,
  peerId: 625045038,
  peerType: 'user',
  senderId: 625045038,
  senderType: 'user',
  createdAt: 1613537815,
  updatedAt: 0,
  text: undefined,
  forwards: MessageForwardsCollection(0) [],
  attachments: [
    LinkAttachment {
      title: 'Яндекс',
      caption: undefined,
      description: 'Найдётся всё',
      url: 'http://yandex.ru/',
      product: undefined,
      button: undefined,
      photo: PhotoAttachment <photo2000046885_457329962> {
        id: 457329962,
        ownerId: 2000046885,
        accessKey: undefined,
        userId: undefined,
        albumId: undefined,
        text: undefined,
        createdAt: undefined,
        height: undefined,
        width: undefined,
        smallSizeUrl: undefined,
        mediumSizeUrl: undefined,
        largeSizeUrl: undefined,
        sizes: undefined
      }
    }
  ],
  isOutbox: false,
  type: 'message',
  subTypes: [
    'message_new'
  ],
  state: {}
}
```
On Matrix side it is rendered as:
```
Link was sent: undefined
```

### PR DESCRIPTION
**Pull request by MurzNN**
Resolves #11

### CODE REVIEW

File: src/vk.ts [hunk 1]
```diff
@@ -543,32 +543,33 @@ export class VkPuppet {
...
+									url = heightMaxUrl;
 								}
 								await this.puppet.sendFileDetect(params, url);
 							} else {
 								await this.puppet.sendFileDetect(params, f["largeSizeUrl"]);
 							}
 						} catch (err) {
 							const opts: IMessageEvent = {
-								body: `Image was sent: ${f["largeSizeUrl"]}`,
+								body: `Image: ${f["image"]["largeSizeUrl"]}`,
```
Comment (inexcode) [inline src/vk.ts:572]: Where did ["image"] come from?

**Review by inexcode — CHANGES_REQUESTED** [review]
Changes also has to be done at https://github.com/innereq/mx-puppet-vk/blob/40c7caf0abd94e781364a00a2642e3a7f533a8c3/src/vk.ts#L708 and https://github.com/innereq/mx-puppet-vk/blob/40c7caf0abd94e781364a00a2642e3a7f533a8c3/src/vk.ts#L748

Should be tested both with user tokens and group tokens.
I may do this later myself.

**Review by inexcode — APPROVED** [review]
